set(CPM_DOWNLOAD_VERSION 0.40.3)
set(CPM_HASH_SUM "2e89a807e906eab270c68c531129dc6b7f989c79a38a4cca7dde0f3ec93d9c68")

if(DEFINED CPM_SOURCE_CACHE AND NOT CPM_SOURCE_CACHE STREQUAL "" AND NOT CPM_SOURCE_CACHE STREQUAL "OFF")
  set(CPM_DOWNLOAD_LOCATION "${CPM_SOURCE_CACHE}/cpm/CPM_${CPM_DOWNLOAD_VERSION}.cmake")
elseif(DEFINED ENV{CPM_SOURCE_CACHE} AND NOT "$ENV{CPM_SOURCE_CACHE}" STREQUAL ""
       AND NOT "$ENV{CPM_SOURCE_CACHE}" STREQUAL "OFF")
  set(CPM_DOWNLOAD_LOCATION "$ENV{CPM_SOURCE_CACHE}/cpm/CPM_${CPM_DOWNLOAD_VERSION}.cmake")
else()
  set(CPM_DOWNLOAD_LOCATION "${CMAKE_BINARY_DIR}/cmake/CPM_${CPM_DOWNLOAD_VERSION}.cmake")
endif()

set(CPM_DOWNLOAD_REQUIRED OFF)
if(NOT EXISTS ${CPM_DOWNLOAD_LOCATION})
  set(CPM_DOWNLOAD_REQUIRED ON)
else()
  file(SIZE ${CPM_DOWNLOAD_LOCATION} CPM_DOWNLOAD_SIZE)
  if(CPM_DOWNLOAD_SIZE EQUAL 0)
    set(CPM_DOWNLOAD_REQUIRED ON)
  endif()
endif()

if(CPM_DOWNLOAD_REQUIRED)
  message(STATUS "Downloading CPM.cmake to ${CPM_DOWNLOAD_LOCATION}")
  file(DOWNLOAD
       https://github.com/cpm-cmake/CPM.cmake/releases/download/v${CPM_DOWNLOAD_VERSION}/CPM.cmake
       ${CPM_DOWNLOAD_LOCATION}
       EXPECTED_HASH SHA256=${CPM_HASH_SUM})
endif()

include(${CPM_DOWNLOAD_LOCATION})
